### ISSUE TITLE
when I install this plugin etc/default/docker is missing

### ISSUE THREAD

**Issue by jodumont** [OpenMediaVault-Plugin-Developers/openmediavault-docker-gui#76]
Hi;

I found a old OMV 2 today which I upgrade to OMV 4 which major issue.
It is on a **PC Engines apu system board** and I retrieve, with few manipulation, root access through SSH
_all this to say I can't reinstall and or have direct access_

Now my concern is when I install openmediavault-docker-gui it result with this error:
```
sed: can't read /etc/default/docker: No such file or directory
dpkg: error processing package openmediavault-docker-gui (--configure):
 subprocess installed post-installation script returned error exit status 2
Processing triggers for libc-bin (2.24-11+deb9u3) ...
Processing triggers for openmediavault (4.1.13-1) ...
Updating locale files ...
Updating file permissions ...
Purging internal cache ...
Restarting engine daemon ...
Errors were encountered while processing:
 openmediavault-docker-gui
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7f186d99e730>
Traceback (most recent call last):
  File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7f186d99e730>
Traceback (most recent call last):
  File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

do somebody could show me is **/etc/default/docker** file and or have an idea on how to fix this ?

Regards!

**Comment by jodumont** [comment]
note, when I install only docker-ce it works well
but it don't generate a /etc/default/docker

**Comment by jodumont** [comment]
I resolve the case by installing docker-ce than installing the plugins
but still; if the plugin create the file, why you didn't simply gave me an example as request and/or a link

**Comment by ryecoaaron** [comment]
@jodumont I don't understand what you thought I should give you?  A link to the code where the plugin creates the file?

**Comment by hooklife** [comment]
@ryecoaaron I have the same problem when installing docker `openmediavault-docker-gui 4.1`

**Comment by ryecoaaron** [comment]
I still don't know why this happens since the plugin creates but I updated the plugin (4.1.1 in repo now) to touch the file at the earliest point the plugin package possibly can.  If this doesn't fix it, it is a problem with the docker-ce package itself and there is nothing else I can do.

code for those who want to see the two places (now) where the file is created:
https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-docker-gui/blob/master/debian/preinst#L3
https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-docker-gui/blob/master/debian/postinst#L25
